image: docker:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    # build web image
    - docker build --pull -t "$CI_REGISTRY_IMAGE/web" -f Dockerfile.web .
    - docker push "$CI_REGISTRY_IMAGE/web"
    - docker tag "$CI_REGISTRY_IMAGE/web" "$CI_REGISTRY_IMAGE/web:$CI_COMMIT_REF_NAME"
    - docker push "$CI_REGISTRY_IMAGE/web:$CI_COMMIT_REF_NAME"
    # build varnish image
    - docker build --pull -t "$CI_REGISTRY_IMAGE/varnish" -f Dockerfile.varnish .
    - docker push "$CI_REGISTRY_IMAGE/varnish"
    - docker tag "$CI_REGISTRY_IMAGE/varnish" "$CI_REGISTRY_IMAGE/varnish:$CI_COMMIT_REF_NAME"
    - docker push "$CI_REGISTRY_IMAGE/varnish:$CI_COMMIT_REF_NAME"
  only:
    - tags

deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment default --stack alod-ch --service web --new-image $CI_REGISTRY_IMAGE/web:$CI_COMMIT_REF_NAME
    - upgrade --environment default --stack alod-ch --service varnish --new-image $CI_REGISTRY_IMAGE/varnish:$CI_COMMIT_REF_NAME
  only:
    - tags
