# used for testing locally
# localhost:8080 and localhost:3000 should serve the same thing,
# except the first one isn't cached and the 2nd one caches queries
version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
    - '8080:8080'

  varnish:
    build:
      context: .
      dockerfile: Dockerfile.varnish
    links:
    - web:alod_web
    ports:
    - '3000:80'
