apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alod-ch
  annotations:
    external-dns.alpha.kubernetes.io/hostname: alod-ch.zazukoians.org,isil-ch.zazukoians.org
spec:
  rules:
  - host: alod.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: varnish
          servicePort: 80
  - host: isil.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: varnish
          servicePort: 80
  - host: "*.alod.ch"
    http:
      paths:
      - path: /
        backend:
          serviceName: varnish
          servicePort: 80
  - host: "*.isil.ch"
    http:
      paths:
      - path: /
        backend:
          serviceName: varnish
          servicePort: 80
