apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alod-ch
  annotations:
    external-dns.alpha.kubernetes.io/hostname: alod-ch.zazukoians.org,isil-ch.zazukoians.org
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/redirect-regex: "^https://(.*)"
    traefik.ingress.kubernetes.io/redirect-replacement: "http://$1"
spec:
  tls:
  - secretName: alod-ch-cert
    hosts:
    - alod.ch
    - data.alod.ch
    - data.bs.alod.ch
    - data.ge.alod.ch
    - data.helveticarchives.alod.ch
    - data.ne.alod.ch
    - data.vs.alod.ch
    - test.alod.ch
    - www.alod.ch
    - isil.ch
    - data.staatsarchiv-bs.ch
  rules:
  - host: alod.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: varnish
          servicePort: 80
  - host: data.alod.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: varnish
          servicePort: 80
  - host: data.bs.alod.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: varnish
          servicePort: 80
  - host: data.ge.alod.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: varnish
          servicePort: 80
  - host: data.helveticarchives.alod.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: varnish
          servicePort: 80
  - host: data.ne.alod.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: varnish
          servicePort: 80
  - host: data.vs.alod.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: varnish
          servicePort: 80
  - host: test.alod.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: varnish
          servicePort: 80
  - host: www.alod.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: varnish
          servicePort: 80
  - host: isil.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: varnish
          servicePort: 80
  - host: data.staatsarchiv-bs.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: varnish
          servicePort: 80
